apiVersion: v2
name: control-panel
description: Liberu Control Panel - Kubernetes-native web hosting control panel
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - control-panel
  - hosting
  - kubernetes
  - laravel
  - web-hosting
home: https://github.com/liberu-control-panel/control-panel-laravel
sources:
  - https://github.com/liberu-control-panel/control-panel-laravel
maintainers:
  - name: Liberu Team
    url: https://liberu.co.uk
icon: https://avatars.githubusercontent.com/u/158830885
