apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

namespace: control-panel-dev

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: control-panel

configMapGenerator:
- name: control-panel-config
  behavior: merge
  literals:
  - APP_ENV=development
  - APP_DEBUG=true
  - LOG_LEVEL=debug

images:
- name: ghcr.io/liberu-control-panel/control-panel-laravel
  newTag: develop
