apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

namespace: control-panel

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
  target:
    kind: Deployment
    name: control-panel

configMapGenerator:
- name: control-panel-config
  behavior: merge
  literals:
  - APP_ENV=production
  - APP_DEBUG=false
  - LOG_LEVEL=warning

images:
- name: ghcr.io/liberu-control-panel/control-panel-laravel
  newTag: latest

resources:
- hpa.yaml
