apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: control-panel

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- pvc.yaml
- mysql-statefulset.yaml
- mysql-service.yaml
- redis.yaml
- nginx-configmap.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

commonLabels:
  app: liberu-control-panel
