apiVersion: v1
kind: Service
metadata:
  name: control-panel-mysql
  namespace: control-panel
  labels:
    app: control-panel
    component: database
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: mysql
  selector:
    app: control-panel
    component: database
  clusterIP: None
