apiVersion: v1
kind: Service
metadata:
  name: control-panel
  namespace: control-panel
  labels:
    app: control-panel
    component: application
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: control-panel
    component: application
